import { importEntries, CUBookEntry } from './import_cu_data.ts';

export const cuRecords: CUBookEntry[] = [
  // F.Y. 2025 to 2026 - Page 1
  { accNo: 'T50771', accDate: '25/11/2025', title: 'Nanoparticulate materials synthesis', author: 'Wiley', publisher: 'Wiley' },
  { accNo: 'T50960', accDate: '19/02/2026', title: 'Neuroscience', author: 'Purves', publisher: 'Oxford University Press' },
  { accNo: 'T50961', accDate: '19/02/2026', title: 'Ganongs review of medical physiology', author: 'Barrett', publisher: 'McGraw Hill Education' },
  { accNo: 'T50962', accDate: '19/02/2026', title: 'Berne & Levy physiology', author: 'Koeppen', publisher: 'Elsevier' },
  { accNo: 'T50963', accDate: '19/02/2026', title: 'Fundamentals of anatomy & physiology', author: 'Martini', publisher: 'Pearson' },
  { accNo: 'T50964', accDate: '19/02/2026', title: 'Harpers illustrated biochemistry', author: 'Kennelly', publisher: 'McGraw Hill Education' },
  { accNo: 'T50953', accDate: '19/02/2026', title: 'Physiological basis of sports and exercise sciences', author: 'Bandyopadhyay', publisher: 'Notion Press' },
  { accNo: 'T50954', accDate: '19/02/2026', title: 'Data analytics in football', author: 'Memmert', publisher: 'Routledge' },
  { accNo: 'T50955', accDate: '19/02/2026', title: 'Developing sport expertise', author: 'Farrow', publisher: 'Routledge' },
  { accNo: 'T50956', accDate: '19/02/2026', title: 'Fatigue in sport and exercise', author: 'Phillips', publisher: 'Routledge' },
  { accNo: 'T50957', accDate: '19/02/2026', title: 'Hypoxia conditioning in health exercise and sport principles mechanisms and applications', author: 'Girard', publisher: 'Routledge' },
  { accNo: 'T50958', accDate: '19/02/2026', title: 'An Introduction to primary physical education', author: 'Griggs', publisher: 'Routledge' },
  { accNo: 'T50959', accDate: '19/02/2026', title: 'Research methods for sport management', author: 'Skinner', publisher: 'Routledge' },
  { accNo: 'T50749', accDate: '24/11/2025', title: 'Statistical Inference', author: 'Casella', publisher: 'Springer' },
  { accNo: 'T50750', accDate: '24/11/2025', title: 'Nature inspired methods', author: 'Bennis Fouad', publisher: 'Academic Press' },
  { accNo: 'T50751', accDate: '24/11/2025', title: 'Data Driven model learning for engineers', author: 'Mercere Guillaume', publisher: 'Springer' },

  // Page 2
  { accNo: 'T50752', accDate: '24/11/2025', title: 'Introduction to cybersecurity', author: 'Sharp', publisher: 'Springer' },
  { accNo: 'T50753', accDate: '24/11/2025', title: 'Algorithms illuminated', author: 'Roughgarden', publisher: 'Soundlikefoam' },
  { accNo: 'T50754', accDate: '24/11/2025', title: 'Statistical inference and machine learning for big data', author: 'Alvo', publisher: 'Springer' },
  { accNo: 'T50755', accDate: '24/11/2025', title: 'Data structures and algorithms in Java', author: 'Myers', publisher: 'Cambridge University Press' },
  { accNo: 'T50756', accDate: '24/11/2025', title: 'Quantum algorithms a survey of applications and end to end complexities', author: 'Dalzell', publisher: 'Cambridge University Press' },
  { accNo: 'T50757', accDate: '24/11/2025', title: 'Embedding in natural language processing', author: 'Pilehvar', publisher: 'Springer' },
  { accNo: 'T50758', accDate: '24/11/2025', title: 'Information retrieval and natural language processing', author: 'Sonawane', publisher: 'Springer' },
  { accNo: 'T50759', accDate: '24/11/2025', title: 'A Course in natural language processing', author: 'Haralambous', publisher: 'Springer' },
  { accNo: 'T50760', accDate: '24/11/2025', title: 'Computer algebra', author: 'Koepf', publisher: 'Springer' },
  { accNo: 'T50761', accDate: '24/11/2025', title: 'Machine learning and artificial intelligence', author: 'Joshi', publisher: 'Springer' },
  { accNo: 'T50762', accDate: '24/11/2025', title: 'Quantum machine learning', author: 'Conti', publisher: 'Springer' },
  { accNo: 'T50763', accDate: '24/11/2025', title: 'Machine learning techniques for cybersecurity', author: 'Bertino', publisher: 'Springer' },
  { accNo: 'T50745', accDate: '19/11/2025', title: 'Problems and Solutions on Optics', author: 'Lai Choy Heng', publisher: 'World Scientific' },
  { accNo: 'T50746', accDate: '19/11/2025', title: 'Light and Xray Optics', author: 'Zolotoyabko Emil', publisher: 'De Gruyter' },
  { accNo: 'T50747', accDate: '19/11/2025', title: 'Close range photogrammetry and 3d imaging', author: 'Luhmann Thomas', publisher: 'De Gruyter' },

  // Page 3
  { accNo: 'T50748', accDate: '19/11/2025', title: 'Optical infrared and radio astronomy', author: 'Poggiani Rosa', publisher: 'De Gruyter' },
  { accNo: 'T50718', accDate: '19/11/2025', title: 'Photonics modelling and design', author: 'Sukhovatkin', publisher: 'CRC Press' },
  { accNo: 'T50719', accDate: '19/11/2025', title: 'Causal physics photons by non interactions of waves', author: 'Roychoudhuri', publisher: 'CRC Press' },
  { accNo: 'T50720', accDate: '19/11/2025', title: 'Engineering optics', author: 'Koki', publisher: 'Springer' },
  { accNo: 'T50721', accDate: '19/11/2025', title: 'Optics for engineers', author: 'Charles', publisher: 'CRC Press' },
  { accNo: 'T50723', accDate: '19/11/2025', title: 'Advanced laser and competing technologies easily explained', author: 'Weber', publisher: 'World Scientific' },
  { accNo: 'T50724', accDate: '19/11/2025', title: 'From photons to higgs a story of light', author: 'Boyd', publisher: 'World Scientific' },
  { accNo: 'T50722', accDate: '19/11/2025', title: 'Foundations of optical system', author: 'Shannon', publisher: 'CRC Press' },
  { accNo: 'T50738', accDate: '19/11/2025', title: 'Gravity from falling apples to supermassive black holes', author: 'Poisson', publisher: 'Oxford University Press' },
  { accNo: 'T50740', accDate: '19/11/2025', title: 'Electromagnetism lectures on theoretical physics', author: 'Sommerfeld', publisher: 'Cambridge University Press' },
  { accNo: 'T50741', accDate: '19/11/2025', title: 'Quantum information a first course', author: 'Barnett', publisher: 'Cambridge University Press' },
  { accNo: 'T50742', accDate: '19/11/2025', title: 'An Introduction to quantum optics and quantum fluctuations', author: 'Milonni', publisher: 'Oxford University Press' },
  { accNo: 'T50743', accDate: '19/11/2025', title: 'Elements of classical and quantum physics', author: 'Ciuchi', publisher: 'Springer' },
  { accNo: 'T50744', accDate: '19/11/2025', title: 'Optical detection of cancer', author: 'Alfano', publisher: 'World Scientific' },
  { accNo: 'T50739', accDate: '19/11/2025', title: 'Quantum mechanics lectures on theoretical physics', author: 'Sommerfeld', publisher: 'Cambridge University Press' },
  { accNo: 'T50725', accDate: '19/11/2025', title: 'Handbook of nonlinear optics', author: 'Sutherland', publisher: 'CRC Press' },

  // Page 4
  { accNo: 'T50726', accDate: '19/11/2025', title: 'Quantum optics', author: 'Orszag', publisher: 'Springer' },
  { accNo: 'T50727', accDate: '19/11/2025', title: 'Modern optics and photonics of nano and microsystems', author: 'Kulchin', publisher: 'CRC Press' },
  { accNo: 'T50728', accDate: '19/11/2025', title: 'Physical optics principles and practices', author: 'Al-Azzawi', publisher: 'CRC Press' },
  { accNo: 'T50729', accDate: '19/11/2025', title: 'Handbook of visual optics', author: 'Artal', publisher: 'CRC Press' },
  { accNo: 'T50730', accDate: '19/11/2025', title: 'Atomic force microscopy understanding basic modes and advanced applications', author: 'Haugstad', publisher: 'Wiley' },
  { accNo: 'T50731', accDate: '19/11/2025', title: 'The quantum matrix', author: 'Kurizki', publisher: 'Oxford University Press' },
  { accNo: 'T50732', accDate: '19/11/2025', title: 'Physics on your feet', author: 'Budker', publisher: 'Oxford University Press' },
  { accNo: 'T50733', accDate: '19/11/2025', title: 'Introduction to quantum computing', author: 'Lapierre', publisher: 'Springer' },
  { accNo: 'T50734', accDate: '19/11/2025', title: 'Computer vision and image analysis', author: 'Umbaugh', publisher: 'CRC Press' },
  { accNo: 'T50735', accDate: '19/11/2025', title: 'Waves in gradient metamaterials', author: 'Shvartsburg', publisher: 'World Scientific' },
  { accNo: 'T50736', accDate: '19/11/2025', title: 'Selected topics in photonic crystals and metamaterials', author: 'Andreone', publisher: 'World Scientific' },
  { accNo: 'T50737', accDate: '19/11/2025', title: 'Digital image processing', author: 'Sundararajan', publisher: 'Springer' },
  { accNo: 'T50898', accDate: '02/01/2026', title: 'A First course in Statistics for signal analysis', author: 'Woyczynski', publisher: 'Springer Nature' },
  { accNo: 'T50899', accDate: '02/01/2026', title: 'Ambient integrated robotics', author: 'Bock Thomas', publisher: 'Cambridge University Press' },
  { accNo: 'T50900', accDate: '02/01/2026', title: 'Modelling and simulation', author: 'Birta Louis G', publisher: 'Springer' },

  // Page 5
  { accNo: 'T50901', accDate: '02/01/2026', title: 'Smart grid using big data analytics', author: 'Qiu Robert C', publisher: 'John Wiley' },
  { accNo: 'T50902', accDate: '02/01/2026', title: 'A Handbook on electrical engineering', author: 'Made Easy Team', publisher: 'Made Easy Publications' },
  { accNo: 'T50903', accDate: '02/01/2026', title: 'A Handbook on instrumentation engineering', author: 'Made Easy Team', publisher: 'Made Easy Publications' },
  { accNo: 'T50904', accDate: '02/01/2026', title: 'GATE 2026 electrical engineering', author: 'Made Easy Team', publisher: 'Made Easy Publications' },
  { accNo: 'T50905', accDate: '02/01/2026', title: 'GATE 2026 instrumentation engineering', author: 'Made Easy Team', publisher: 'Made Easy Publications' },
  { accNo: 'T50906', accDate: '02/01/2026', title: 'Machine learning in healthcare', author: 'Sinha G R', publisher: 'CRC Press' },
  { accNo: 'T50908', accDate: '02/01/2026', title: 'Process control principles and applications', author: 'Bhanot S', publisher: 'Oxford University Press' },
  { accNo: 'T50909', accDate: '02/01/2026', title: 'Basic electrical engineering', author: 'Pal J', publisher: 'Aryan Publishing House' },
  { accNo: 'T50910', accDate: '02/01/2026', title: 'Basic electrical engineering', author: 'Pal J', publisher: 'Aryan Publishing House' },
  { accNo: 'T50907', accDate: '02/01/2026', title: 'Fundamentals of internet of things', author: 'Kumar S', publisher: 'CRC Press' },
  { accNo: 'T50911', accDate: '02/01/2026', title: 'Machine learning', author: 'Zhou', publisher: 'Springer' },
  { accNo: 'T50912', accDate: '02/01/2026', title: 'Deep learning foundations and concepts', author: 'Bishop', publisher: 'Springer' },
  { accNo: 'T50913', accDate: '02/01/2026', title: 'Explorations in time frequency analysis', author: 'Flandrin', publisher: 'Cambridge University Press' },
  { accNo: 'T50918', accDate: '05/01/2026', title: 'Machine learning', author: 'Zhou', publisher: 'Springer' },
  { accNo: 'T50919', accDate: '05/01/2026', title: 'Op AMP applications handbook', author: 'Jung', publisher: 'Springer' },
  { accNo: 'T50920', accDate: '05/01/2026', title: 'Automotive control', author: 'Isermann', publisher: 'Springer' },
  { accNo: 'T50921', accDate: '05/01/2026', title: 'Linear algebra with Python', author: 'Tsukada', publisher: 'Springer' },
  { accNo: 'T50922', accDate: '05/01/2026', title: 'Digital signal processing', author: 'Esakkirajan', publisher: 'Springer' },

  // Page 6 & 7 (ML, IoT, Python)
  { accNo: 'T50923', accDate: '05/01/2026', title: 'Musicality of human brain through fractal analytics', author: 'Ghosh', publisher: 'Springer' },
  { accNo: 'T50924', accDate: '05/01/2026', title: 'Grid forming converters', author: 'Fang', publisher: 'Academic Press' },
  { accNo: 'T50925', accDate: '05/01/2026', title: 'Control Engineering', author: 'Keviczky', publisher: 'Springer' },
  { accNo: 'T50926', accDate: '05/01/2026', title: 'Advanced high voltage power device concepts', author: 'Baliga', publisher: 'Springer' },
  { accNo: 'T50927', accDate: '05/01/2026', title: 'Automotive embedded systems', author: 'Neelaveni', publisher: 'Springer' },
  { accNo: 'T50928', accDate: '05/01/2026', title: 'Machine learning with Python', author: 'Bhatia', publisher: 'Cambridge University Press' },
  { accNo: 'T50929', accDate: '05/01/2026', title: 'Machine learning with Python', author: 'Bhatia', publisher: 'Cambridge University Press' },
  { accNo: 'T50930', accDate: '05/01/2026', title: 'Machine learning with Python', author: 'Bhatia', publisher: 'Cambridge University Press' },
  { accNo: 'T50931', accDate: '05/01/2026', title: 'Machine learning a hands on approach', author: 'Robin', publisher: 'Universities Press' },
  { accNo: 'T50932', accDate: '05/01/2026', title: 'Machine learning theory and practice', author: 'Murty', publisher: 'Universities Press' },
  { accNo: 'T50933', accDate: '05/01/2026', title: 'Internet of things', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50935', accDate: '05/01/2026', title: 'Internet of things', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50934', accDate: '05/01/2026', title: 'Internet of things', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50937', accDate: '05/01/2026', title: 'Python programming', author: 'Goel', publisher: 'Universities Press' },
  { accNo: 'T50938', accDate: '05/01/2026', title: 'Python programming', author: 'Goel', publisher: 'Universities Press' },
  { accNo: 'T50936', accDate: '05/01/2026', title: 'Python programming', author: 'Goel', publisher: 'Universities Press' },
  { accNo: 'T50939', accDate: '05/01/2026', title: 'Python programming', author: 'Satyanarayana', publisher: 'Universities Press' },
  { accNo: 'T50940', accDate: '05/01/2026', title: 'Understanding renewable energy systems', author: 'Quaschning', publisher: 'Routledge' },
  { accNo: 'T50914', accDate: '05/01/2026', title: 'Introduction to microcontroller programming for power', author: 'Matti Rossi N', publisher: 'CRC Press' },
  { accNo: 'T50915', accDate: '05/01/2026', title: 'Emerging power converters for renewable energy and electric vehicles', author: 'Md. Rabiul Islar', publisher: 'CRC Press' },
  { accNo: 'T50916', accDate: '05/01/2026', title: 'Introduction to electromagnetism', author: 'Sible Martin J N', publisher: 'CRC Press' },
  { accNo: 'T50917', accDate: '05/01/2026', title: 'Machine learning with python', author: 'Bhatia Parteek', publisher: 'Cambridge University Press' },
  { accNo: 'T50772', accDate: '24/11/2025', title: 'An Introduction to Machine Learning', author: 'Kubat', publisher: 'Springer' },
  { accNo: 'T50773', accDate: '24/11/2025', title: 'Data Structures and Algorithms Using Python', author: 'Saha', publisher: 'Cambridge University Press' },
  { accNo: 'T50774', accDate: '24/11/2025', title: 'Data Structures and Algorithms Using Python', author: 'Saha', publisher: 'Cambridge University Press' },
  { accNo: 'T50775', accDate: '24/11/2025', title: 'Data Structures and Algorithms Using Python', author: 'Saha', publisher: 'Cambridge University Press' },
  { accNo: 'T50776', accDate: '24/11/2025', title: 'Data Structures and Algorithms Using Python', author: 'Saha', publisher: 'Cambridge University Press' },
  { accNo: 'T50777', accDate: '24/11/2025', title: 'Data Structures and Algorithms Using Python', author: 'Saha', publisher: 'Cambridge University Press' },
  { accNo: 'T50782', accDate: '24/11/2025', title: 'Introduction to Iot', author: 'Misra', publisher: 'Cambridge University Press' },
  { accNo: 'T50781', accDate: '24/11/2025', title: 'Introduction to Iot', author: 'Misra', publisher: 'Cambridge University Press' },
  { accNo: 'T50780', accDate: '24/11/2025', title: 'Introduction to Iot', author: 'Misra', publisher: 'Cambridge University Press' },
  { accNo: 'T50779', accDate: '24/11/2025', title: 'Introduction to Iot', author: 'Misra', publisher: 'Cambridge University Press' },
  { accNo: 'T50778', accDate: '24/11/2025', title: 'Introduction to Iot', author: 'Misra', publisher: 'Cambridge University Press' },

  // Page 8 & 9 (Algorithms, Distributed Computing, Blockchain)
  { accNo: 'T51013', accDate: '13/02/2026', title: 'Machine learning', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51014', accDate: '13/02/2026', title: 'Machine learning', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51016', accDate: '13/02/2026', title: 'Distributed computing', author: 'Cambridge Press Team', publisher: 'Cambridge University Press' },
  { accNo: 'T51015', accDate: '13/02/2026', title: 'Distributed computing', author: 'Cambridge Press Team', publisher: 'Cambridge University Press' },
  { accNo: 'T51017', accDate: '13/02/2026', title: 'Probability and statistics for data science', author: 'Cambridge Press Team', publisher: 'Cambridge University Press' },
  { accNo: 'T51018', accDate: '13/02/2026', title: 'Blockchain technology', author: 'Nakamoto Group', publisher: 'Academic Press' },
  { accNo: 'T51019', accDate: '13/02/2026', title: 'Blockchain technology', author: 'Nakamoto Group', publisher: 'Academic Press' },
  { accNo: 'T51020', accDate: '13/02/2026', title: 'Blockchain technology', author: 'Nakamoto Group', publisher: 'Academic Press' },
  { accNo: 'T51021', accDate: '13/02/2026', title: 'Introduction to data science', author: 'Pearson Education', publisher: 'Pearson' },
  { accNo: 'T51022', accDate: '13/02/2026', title: 'Operations research', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51024', accDate: '13/02/2026', title: 'Operations research', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51025', accDate: '13/02/2026', title: 'Operations research', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51023', accDate: '13/02/2026', title: 'Operations research', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51027', accDate: '13/02/2026', title: 'Fundamentals of computer algorithms', author: 'Horowitz & Sahni', publisher: 'Universities Press' },
  { accNo: 'T51029', accDate: '13/02/2026', title: 'Fundamentals of computer algorithms', author: 'Horowitz & Sahni', publisher: 'Universities Press' },
  { accNo: 'T51028', accDate: '13/02/2026', title: 'Fundamentals of computer algorithms', author: 'Horowitz & Sahni', publisher: 'Universities Press' },
  { accNo: 'T51030', accDate: '13/02/2026', title: 'Fundamentals of computer algorithms', author: 'Horowitz & Sahni', publisher: 'Universities Press' },
  { accNo: 'T51026', accDate: '13/02/2026', title: 'Fundamentals of computer algorithms', author: 'Horowitz & Sahni', publisher: 'Universities Press' },
  { accNo: 'T51031', accDate: '13/02/2026', title: 'Business analytics', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51033', accDate: '13/02/2026', title: 'Business analytics', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51034', accDate: '13/02/2026', title: 'Business analytics', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51032', accDate: '13/02/2026', title: 'Business analytics', author: 'Universities Press Team', publisher: 'Universities Press' },
  { accNo: 'T51036', accDate: '13/02/2026', title: 'Wireless communications', author: 'Goldsmith', publisher: 'Cambridge University Press' },
  { accNo: 'T51038', accDate: '13/02/2026', title: 'Wireless communications', author: 'Goldsmith', publisher: 'Cambridge University Press' },
  { accNo: 'T51037', accDate: '13/02/2026', title: 'Wireless communications', author: 'Goldsmith', publisher: 'Cambridge University Press' },
  { accNo: 'T51039', accDate: '13/02/2026', title: 'Wireless communications', author: 'Goldsmith', publisher: 'Cambridge University Press' },
  { accNo: 'T51035', accDate: '13/02/2026', title: 'Wireless communications', author: 'Goldsmith', publisher: 'Cambridge University Press' },
  { accNo: 'T51040', accDate: '13/02/2026', title: 'Randomized algorithms', author: 'Motwani & Raghavan', publisher: 'Cambridge University Press' },
  { accNo: 'T50975', accDate: '18/02/2026', title: 'Introduction to quantum algorithms', author: 'Buchmann', publisher: 'American Mathematical Society' },
  { accNo: 'T50976', accDate: '18/02/2026', title: 'Big data analytics', author: 'Chandramouli', publisher: 'Universities Press' },
  { accNo: 'T50977', accDate: '18/02/2026', title: 'Big data analytics', author: 'Chandramouli', publisher: 'Universities Press' },
  { accNo: 'T50979', accDate: '18/02/2026', title: 'Machine learning a hands on approach', author: 'Robin', publisher: 'Universities Press' },
  { accNo: 'T50978', accDate: '18/02/2026', title: 'Machine learning a hands on approach', author: 'Robin', publisher: 'Universities Press' },
  { accNo: 'T50980', accDate: '18/02/2026', title: 'Building quantum computers', author: 'Majidy', publisher: 'Cambridge University Press' },
  { accNo: 'T50981', accDate: '18/02/2026', title: 'Cloud computing a hands on approach', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50982', accDate: '18/02/2026', title: 'Cloud computing a hands on approach', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50983', accDate: '18/02/2026', title: 'Cloud computing a hands on approach', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50984', accDate: '18/02/2026', title: 'Cloud computing a hands on approach', author: 'Bahga', publisher: 'Universities Press' },
  { accNo: 'T50985', accDate: '18/02/2026', title: 'Natural language processing with transformers building language applications with hugging face', author: 'Tunstall', publisher: 'Shroff Publishers' },
  { accNo: 'T50986', accDate: '18/02/2026', title: 'Statistical inference', author: 'Casella', publisher: 'Cengage' },
  { accNo: 'T50987', accDate: '18/02/2026', title: 'Time series analysis', author: 'Hamilton M J D', publisher: 'Levant Books' },
  { accNo: 'T50988', accDate: '18/02/2026', title: 'Data structures and algorithm analysis in C', author: 'Weiss', publisher: 'Pearson' },
  { accNo: 'T50989', accDate: '18/02/2026', title: 'Data structures and algorithm analysis in C', author: 'Weiss', publisher: 'Pearson' },
  { accNo: 'T50990', accDate: '18/02/2026', title: 'Statistical inference and machine learning for big data', author: 'Alvo', publisher: 'Springer' },
  { accNo: 'T50991', accDate: '18/02/2026', title: 'Introduction to time series and forecasting', author: 'Brockwell', publisher: 'Springer' },
  { accNo: 'T50968', accDate: '18/02/2026', title: 'Machine learning', author: 'Zhou', publisher: 'Springer' },
  { accNo: 'T50969', accDate: '18/02/2026', title: 'Deep learning foundations and concepts', author: 'Bishop', publisher: 'Springer' },
  { accNo: 'T50970', accDate: '18/02/2026', title: 'Data mining concepts and techniques', author: 'Han', publisher: 'Elsevier' },
  { accNo: 'T50965', accDate: '18/02/2026', title: 'Machine learning with Python principles and practical techniques', author: 'Bhatia Parteek', publisher: 'Cambridge University Press' },
  { accNo: 'T50966', accDate: '18/02/2026', title: 'Machine learning with Python principles and practical techniques', author: 'Bhatia Parteek', publisher: 'Cambridge University Press' },
  { accNo: 'T50967', accDate: '18/02/2026', title: 'Deep learning machine learning and IoT in biomedical and health informatics techniques and applications', author: 'Das Sujata', publisher: 'CRC Press' },

  // Linear Algebra, Combinatorics, Networks (Pages 10–13)
  { accNo: 'T51041', accDate: '18/02/2026', title: 'Advanced linear algebra', author: 'Cooperstein Bruce', publisher: 'CRC Press' },
  { accNo: 'T51042', accDate: '18/02/2026', title: 'Permutation and combination', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51043', accDate: '18/02/2026', title: 'Permutation and combination', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51045', accDate: '18/02/2026', title: 'Permutation and combination', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51044', accDate: '18/02/2026', title: 'Permutation and combination', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51046', accDate: '18/02/2026', title: 'Permutation and combination', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51051', accDate: '18/02/2026', title: 'Probability and statistics', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51049', accDate: '18/02/2026', title: 'Probability and statistics', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51050', accDate: '18/02/2026', title: 'Probability and statistics', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51048', accDate: '18/02/2026', title: 'Probability and statistics', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51047', accDate: '18/02/2026', title: 'Probability and statistics', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51052', accDate: '18/02/2026', title: 'Linear algebra', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51053', accDate: '18/02/2026', title: 'Linear algebra', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51055', accDate: '18/02/2026', title: 'Linear algebra', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51054', accDate: '18/02/2026', title: 'Linear algebra', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51056', accDate: '18/02/2026', title: 'Linear algebra', author: 'Chakrabarti A', publisher: 'Levant Books' },
  { accNo: 'T51059', accDate: '18/02/2026', title: 'Ad Hoc and sensor network', author: 'Cordeoro S', publisher: 'World Scientific' },
  { accNo: 'T51060', accDate: '18/02/2026', title: 'Ad Hoc and sensor network', author: 'Cordeoro S', publisher: 'World Scientific' },
  { accNo: 'T51058', accDate: '18/02/2026', title: 'Ad Hoc and sensor network', author: 'Cordeoro S', publisher: 'World Scientific' },
  { accNo: 'T51057', accDate: '18/02/2026', title: 'Ad Hoc and sensor network', author: 'Cordeoro S', publisher: 'World Scientific' },
  { accNo: 'T51061', accDate: '18/02/2026', title: 'Modern information retrieval', author: 'Yates', publisher: 'Pearson' },
  { accNo: 'T51062', accDate: '18/02/2026', title: 'Mathematics for machine learning', author: 'Deisenroth', publisher: 'Cambridge University Press' },
  { accNo: 'T51063', accDate: '18/02/2026', title: 'Mathematics for machine learning', author: 'Deisenroth', publisher: 'Cambridge University Press' },
  { accNo: 'T51064', accDate: '18/02/2026', title: 'Problems on algorithms a comprehensive exercise', author: 'Izadkhah', publisher: 'Springer' },
  { accNo: 'T51065', accDate: '18/02/2026', title: 'Techniques for designing and analyzing algorithms', author: 'Stinson', publisher: 'CRC Press' },
  { accNo: 'T51066', accDate: '18/02/2026', title: 'Introduction to formal languages and automation', author: 'Linz', publisher: 'Jones and Bartlett Learning' },
  { accNo: 'T51067', accDate: '18/02/2026', title: 'Introduction to formal languages and automation', author: 'Linz', publisher: 'Jones and Bartlett Learning' },
  { accNo: 'T51069', accDate: '18/02/2026', title: 'Introduction to formal languages and automation', author: 'Linz', publisher: 'Jones and Bartlett Learning' },
  { accNo: 'T51068', accDate: '18/02/2026', title: 'Introduction to formal languages and automation', author: 'Linz', publisher: 'Jones and Bartlett Learning' },
  { accNo: 'T51000', accDate: '18/02/2026', title: 'Wireless internet of things', author: 'Agyei Gyasi', publisher: 'World Scientific' },
  { accNo: 'T51001', accDate: '18/02/2026', title: 'How to think algorithm', author: 'Edmonds', publisher: 'Cambridge University Press' },
  { accNo: 'T51002', accDate: '18/02/2026', title: 'Genetic algorithms and genetic programming', author: 'Affenzeller', publisher: 'CRC Press' },
  { accNo: 'T51003', accDate: '18/02/2026', title: 'Data science for professionals experimental', author: 'Das N C', publisher: 'Shroff Publishers' },
  { accNo: 'T51004', accDate: '18/02/2026', title: 'Elliptic curves number theory and cryptography', author: 'Washington', publisher: 'CRC Press' },
  { accNo: 'T51005', accDate: '18/02/2026', title: 'A Computational approach to statistical learning', author: 'Arnold Taylor', publisher: 'CRC Press' },
  { accNo: 'T51006', accDate: '18/02/2026', title: 'Python for finance mastering data driven', author: 'Hilpisch Yves', publisher: 'Shroff Publishers' },
  { accNo: 'T51007', accDate: '18/02/2026', title: 'Business analytics the science of data driven', author: 'Kumar U Dinersh', publisher: 'Wiley India' },
  { accNo: 'T51008', accDate: '18/02/2026', title: 'Linear models with Python', author: 'Faraway', publisher: 'CRC Press' },
  { accNo: 'T51009', accDate: '18/02/2026', title: 'Natural language processing with transformers', author: 'Tunstall Lewis', publisher: 'Shroff Publishers' },
  { accNo: 'T51010', accDate: '18/02/2026', title: 'Introduction to applied linear algebra', author: 'Boyd', publisher: 'Cambridge University Press' },
  { accNo: 'T51011', accDate: '18/02/2026', title: 'Queueing theory a linear algebraic approach', author: 'Lipsky L', publisher: 'Springer' },
  { accNo: 'T51012', accDate: '18/02/2026', title: 'Pattern recognition and big data', author: 'Pal Amita', publisher: 'World Scientific' },
  { accNo: 'T50992', accDate: '18/02/2026', title: 'Introduction to information retrieval', author: 'Manning', publisher: 'Cambridge University Press' },
  { accNo: 'T50993', accDate: '18/02/2026', title: 'Quantum computation and quantum information', author: 'Nielsen & Chuang', publisher: 'Cambridge University Press' },
  { accNo: 'T50994', accDate: '18/02/2026', title: 'Wireless communication', author: 'Goldsmith', publisher: 'Cambridge University Press' },
  { accNo: 'T50996', accDate: '18/02/2026', title: 'Switching and finite automation theory', author: 'Kohavi', publisher: 'Cambridge University Press' },
  { accNo: 'T50997', accDate: '18/02/2026', title: 'Computer networks a systems approach', author: 'Peterson Larry L', publisher: 'Elsevier' },
  { accNo: 'T50998', accDate: '18/02/2026', title: 'An Introduction to the bootstrap', author: 'Efron Bradley', publisher: 'Chapman and Hall' },
  { accNo: 'T50999', accDate: '18/02/2026', title: 'High dimensional statistics', author: 'Wainwright', publisher: 'Cambridge University Press' },
  { accNo: 'T50971', accDate: '18/02/2026', title: 'Artificial intelligence a modern approach', author: 'Russell & Norvig', publisher: 'Pearson' },
  { accNo: 'T50972', accDate: '18/02/2026', title: 'Artificial intelligence a modern approach', author: 'Russell & Norvig', publisher: 'Pearson' },
  { accNo: 'T50973', accDate: '18/02/2026', title: 'Probability and random processes', author: 'Miller', publisher: 'Elsevier' },
  { accNo: 'T50974', accDate: '18/02/2026', title: 'Data mining concepts and techniques', author: 'Han', publisher: 'Elsevier' },

  // Chemical Engineering, Polymers, Textiles (Pages 14–23)
  { accNo: 'T50793', accDate: '18/12/2025', title: 'Conducting Polymers', author: 'Otero', publisher: 'Cambridge University Press' },
  { accNo: 'T50794', accDate: '18/12/2025', title: 'New Horizons in predictive drug Metabolism and Pharmacokinetics', author: 'Wilson', publisher: 'Cambridge University Press' },
  { accNo: 'T50839', accDate: '18/12/2025', title: 'Biorefineries', author: 'Alzate', publisher: 'CRC Press' },
  { accNo: 'T50840', accDate: '18/12/2025', title: 'Green Petroleum', author: 'Islam', publisher: 'Wiley' },
  { accNo: 'T50841', accDate: '18/12/2025', title: 'Smart materials for drug delivery', author: 'Lorenzo Alvarez', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50842', accDate: '18/12/2025', title: 'Smart materials for drug delivery', author: 'Lorenzo Alvarez', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50843', accDate: '18/12/2025', title: 'Special inorganic cements', author: 'Odler', publisher: 'CRC Press' },
  { accNo: 'T50844', accDate: '18/12/2025', title: 'Cement Chemistry', author: 'Richardson', publisher: 'Emerald Publishing' },
  { accNo: 'T50845', accDate: '18/12/2025', title: 'Fundamental Biomaterials', author: 'Thomas', publisher: 'Woodhead Publishing' },
  { accNo: 'T50846', accDate: '18/12/2025', title: 'Vegetable oil based Polymers', author: 'Karak', publisher: 'Woodhead Publishing' },
  { accNo: 'T50847', accDate: '18/12/2025', title: 'Handbook of natural gas analysis', author: 'Speight', publisher: 'Wiley' },
  { accNo: 'T50848', accDate: '18/12/2025', title: 'Fundamentals of petrophysics', author: 'Yang', publisher: 'Springer' },
  { accNo: 'T50849', accDate: '18/12/2025', title: 'Enriched methane', author: 'Falco', publisher: 'Springer' },
  { accNo: 'T50850', accDate: '18/12/2025', title: 'Advanced petroleum refining', author: 'Sarkar', publisher: 'Khanna' },
  { accNo: 'T50851', accDate: '18/12/2025', title: 'Objective type questions and answers in Chemical Engineering', author: 'Gupta', publisher: 'Khanna' },
  { accNo: 'T50852', accDate: '18/12/2025', title: 'Objective type questions and answers', author: 'Prasad', publisher: 'Khanna' },
  { accNo: 'T50853', accDate: '18/12/2025', title: 'Textbook of medicinal chemistry', author: 'Alagarsamy', publisher: 'CBS Publishers' },
  { accNo: 'T50854', accDate: '18/12/2025', title: 'Textbook of medicinal chemistry', author: 'Alagarsamy', publisher: 'CBS Publishers' },
  { accNo: 'T50855', accDate: '18/12/2025', title: 'Textbook of medicinal chemistry', author: 'Alagarsamy', publisher: 'CBS Publishers' },
  { accNo: 'T50856', accDate: '18/12/2025', title: 'Textbook of medicinal chemistry', author: 'Alagarsamy', publisher: 'CBS Publishers' },
  { accNo: 'T50857', accDate: '18/12/2025', title: 'Pharmaceutics I', author: 'Mehta', publisher: 'Vallabh Prakashan' },
  { accNo: 'T50795', accDate: '18/12/2025', title: 'A First course in iron and steelmaking', author: 'Mazumdar D', publisher: 'Universities Press' },
  { accNo: 'T50797', accDate: '18/12/2025', title: 'A First course in iron and steelmaking', author: 'Mazumdar D', publisher: 'Universities Press' },
  { accNo: 'T50796', accDate: '18/12/2025', title: 'A First course in iron and steelmaking', author: 'Mazumdar D', publisher: 'Universities Press' },
  { accNo: 'T50798', accDate: '18/12/2025', title: 'Pem electrolysis for hydrogen production principles and applications', author: 'Bessarabov D', publisher: 'CRC Press' },
  { accNo: 'T50799', accDate: '17/12/2025', title: 'Experimental thermodynamics volume', author: 'Bedeaux', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50783', accDate: '18/12/2025', title: 'Design characterization and fabrication of polymer scaffolds for tissue engineering', author: 'Chattopadhyay', publisher: 'Academic Press' },
  { accNo: 'T50784', accDate: '18/12/2025', title: 'Design characterization and fabrication of polymer scaffolds for tissue engineering', author: 'Chattopadhyay', publisher: 'Academic Press' },
  { accNo: 'T50785', accDate: '18/12/2025', title: 'Design characterization and fabrication of polymer scaffolds for tissue engineering', author: 'Chattopadhyay', publisher: 'Academic Press' },
  { accNo: 'T50786', accDate: '18/12/2025', title: 'Polymers for pem fuel cells', author: 'Pu', publisher: 'Wiley' },
  { accNo: 'T50787', accDate: '18/12/2025', title: 'Healable polymer systems', author: 'Hayes', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50788', accDate: '18/12/2025', title: 'Poly Lactic acid science and technology processing properties additives and applications', author: 'Jimenez', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50789', accDate: '18/12/2025', title: 'Polymeric and self assembled hydrogels from fundamental understanding to applications', author: 'Loh', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50790', accDate: '18/12/2025', title: 'Polymeric materials with antimicrobial activity from synthesis to applications', author: 'Munoz Bonilla', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50791', accDate: '18/12/2025', title: 'Functional polymeric composites macro to nanoscales', author: 'Chia', publisher: 'Apple Academic Press' },
  { accNo: 'T50792', accDate: '18/12/2025', title: 'Handbook of nanocomposite supercapacitor materials 1', author: 'Kar', publisher: 'Springer' },
  { accNo: 'T50800', accDate: '17/12/2025', title: 'Dynamic systems modeling simulation and analysis', author: 'Vu & Esfandiari', publisher: 'Cambridge University Press' },
  { accNo: 'T50801', accDate: '17/12/2025', title: 'Dynamic systems modeling simulation and analysis', author: 'Vu & Esfandiari', publisher: 'Cambridge University Press' },
  { accNo: 'T50802', accDate: '17/12/2025', title: 'Understanding process dynamics and control', author: 'Kravaris', publisher: 'Cambridge University Press' },
  { accNo: 'T50803', accDate: '17/12/2025', title: 'Applied Engineering analysis', author: 'Hsu', publisher: 'Wiley' },
  { accNo: 'T50804', accDate: '17/12/2025', title: 'Applied Engineering analysis', author: 'Hsu', publisher: 'Wiley' },
  { accNo: 'T50805', accDate: '17/12/2025', title: 'Sustainable environmental engineering', author: 'Tang', publisher: 'Wiley' },
  { accNo: 'T50806', accDate: '17/12/2025', title: 'Experimental thermodynamics volume x', author: 'Bedeaux', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50807', accDate: '17/12/2025', title: 'Principles of turbulence control', author: 'Fan', publisher: 'Wiley' },
  { accNo: 'T50808', accDate: '17/12/2025', title: 'Nuclear energy for hydrogen generation', author: 'Zohuri', publisher: 'Springer Nature' },

  // Coulson and Richardson Chemical Engineering series (Multiple copies)
  { accNo: 'T50809', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50811', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50813', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50815', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50817', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50819', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50821', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50822', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50820', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50818', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50816', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50814', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50812', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },
  { accNo: 'T50810', accDate: '17/12/2025', title: 'Coulson and Richardsons chemical engineering solutions', author: 'Backhurst J R', publisher: 'Elsevier' },

  // Piping, Chemical Process Design, Fluid Mechanics
  { accNo: 'T50823', accDate: '17/12/2025', title: 'Foundations of fluid mechanics', author: 'Kiselev', publisher: 'Springer Nature' },
  { accNo: 'T50824', accDate: '17/12/2025', title: 'Foundations of fluid mechanics', author: 'Kiselev', publisher: 'Springer Nature' },
  { accNo: 'T50826', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50827', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50828', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50829', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50830', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50831', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50825', accDate: '17/12/2025', title: 'Piping design handbook', author: 'McKetta', publisher: 'Marcel Dekker' },
  { accNo: 'T50832', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },
  { accNo: 'T50838', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },
  { accNo: 'T50837', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },
  { accNo: 'T50836', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },
  { accNo: 'T50835', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },
  { accNo: 'T50834', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },
  { accNo: 'T50833', accDate: '17/12/2025', title: 'Chemical process design and integration', author: 'Smith', publisher: 'Wiley India' },

  // GATE Guides, Nanotechnology, Electronics
  { accNo: 'T50858', accDate: '30/12/2025', title: 'GATE tutor Electronics & communication Engineering exam 2026', author: 'Goel', publisher: 'Arihant Publications' },
  { accNo: 'T50859', accDate: '30/12/2025', title: 'GATE Tutor computer Science & Technology exam 2026', author: 'Kirupani', publisher: 'Arihant Publications' },
  { accNo: 'T50860', accDate: '30/12/2025', title: 'Deep learning', author: 'Bishop', publisher: 'Springer' },
  { accNo: 'T50861', accDate: '30/12/2025', title: 'Nanofabrication and its application in renewable energy', author: 'Zhang', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50862', accDate: '30/12/2025', title: 'Materials challenges inorganic Photovoltaic solar energy', author: 'Irvine', publisher: 'Royal Society of Chemistry' },
  { accNo: 'T50863', accDate: '30/12/2025', title: 'Graphene nanostructures modeling simulation and applications in Electronics and Photonics', author: 'Banadaki', publisher: 'Jenny Stanford' },
  { accNo: 'T50864', accDate: '30/12/2025', title: 'Optical switching networks', author: 'Maier', publisher: 'Cambridge University Press' },
  { accNo: 'T50865', accDate: '30/12/2025', title: 'Remote sensing Geology', author: 'Gupta', publisher: 'Springer' },
  { accNo: 'T50866', accDate: '30/12/2025', title: 'Robust sram designs and analysis', author: 'Singh', publisher: 'Springer' },
  { accNo: 'T50867', accDate: '30/12/2025', title: '3D Tcad simulation for semiconductor processes devices and Optoelectronics', author: 'Li', publisher: 'Springer' },
  { accNo: 'T50868', accDate: '30/12/2025', title: 'Key technologies for 5G Wireless systems', author: 'Wong', publisher: 'Cambridge University Press' },
  { accNo: 'T50869', accDate: '30/12/2025', title: 'Photonics volume 3', author: 'Andrewes', publisher: 'Wiley' },
  { accNo: 'T50870', accDate: '30/12/2025', title: 'Electronic and Optical properties of D band perovskites', author: 'Wolfram', publisher: 'Cambridge University Press' },
  { accNo: 'T50871', accDate: '30/12/2025', title: 'Radio resource management in wireless networks', author: 'Hossain', publisher: 'Cambridge University Press' },
  { accNo: 'T50872', accDate: '30/12/2025', title: 'Quantum information', author: 'Barnett Stephen', publisher: 'Oxford University Press' },
  { accNo: 'T50873', accDate: '30/12/2025', title: 'Communication principles for data science', author: 'Suh Changho', publisher: 'Springer' },
  { accNo: 'T50874', accDate: '30/12/2025', title: 'EEG based brain computer interfaces', author: 'Bansal Dipali', publisher: 'Academic Press' },
  { accNo: 'T50875', accDate: '30/12/2025', title: 'Essentials of cloud computing', author: 'Suriyanarayan', publisher: 'Springer' },
  { accNo: 'T50876', accDate: '30/12/2025', title: 'Topics in signal processing', author: 'Dutta Roy Suhash Chandra', publisher: 'Springer' },
  { accNo: 'T50877', accDate: '30/12/2025', title: 'Evolutionary multi task optimization', author: 'Feng Liang', publisher: 'Springer' },
  { accNo: 'T50878', accDate: '30/12/2025', title: 'Quantum nano plasmonics', author: 'Jacak W A', publisher: 'Cambridge University Press' },
  { accNo: 'T50882', accDate: '31/12/2025', title: 'Introduction to computational engineering with matlab', author: 'Bower', publisher: 'CRC Press' },
  { accNo: 'T50883', accDate: '31/12/2025', title: 'Internet of things', author: 'Hassan Q F', publisher: 'CRC Press' },
  { accNo: 'T50884', accDate: '31/12/2025', title: 'Introduction to engineering and scientific computing with python', author: 'Chapra S C', publisher: 'CRC Press' },
  { accNo: 'T50885', accDate: '31/12/2025', title: 'Multinary alloys based on III V semiconductors', author: 'Tomashyk V', publisher: 'CRC Press' },
  { accNo: 'T50886', accDate: '31/12/2025', title: 'Continuous signals and systems with matlab', author: 'Eiali T S', publisher: 'CRC Press' },
  { accNo: 'T50887', accDate: '31/12/2025', title: 'Optical properties of solids an introductory text books', author: 'Locharoenr', publisher: 'Pan Stanford' },
  { accNo: 'T50879', accDate: '31/12/2025', title: 'Artificial intelligence', author: 'Russell', publisher: 'Pearson' },
  { accNo: 'T50880', accDate: '31/12/2025', title: 'Reimagining data visualization using Python', author: 'Acharya', publisher: 'Wiley India' },
  { accNo: 'T50881', accDate: '31/12/2025', title: 'Deep learning with tensorflow JS projects', author: 'Sharma', publisher: 'Wiley India' },
  { accNo: 'T50888', accDate: '02/01/2026', title: 'Research Methodology', author: 'Kothari C R', publisher: 'New Age Books' },
  { accNo: 'T50889', accDate: '02/01/2026', title: 'Fundamentals of optical networks and components', author: 'Sahu P P', publisher: 'CRC Press' },
  { accNo: 'T50890', accDate: '02/01/2026', title: 'Principles of photonic integrated circuits', author: 'Meng X', publisher: 'Springer' },
  { accNo: 'T50891', accDate: '02/01/2026', title: 'Quantum optics including noise reduction trapped', author: 'Orszag M', publisher: 'Springer' },
  { accNo: 'T50892', accDate: '02/01/2026', title: 'Quantum Optics', author: 'Meystre P', publisher: 'Springer' },
  { accNo: 'T50893', accDate: '02/01/2026', title: 'A Functional start to computing with Python', author: 'Herman T', publisher: 'CRC Press' },
  { accNo: 'T50894', accDate: '02/01/2026', title: 'Interoperability in IOT for smart systems', author: 'Roy M', publisher: 'CRC Press' },
  { accNo: 'T50895', accDate: '02/01/2026', title: 'Python programming', author: 'Mehra R', publisher: 'Cengage' },
  { accNo: 'T50896', accDate: '02/01/2026', title: 'Python programming for the absolute beginner', author: 'Dawson', publisher: 'Cengage' },
  { accNo: 'T50897', accDate: '02/01/2026', title: 'Artificial intelligence', author: 'Kaushik', publisher: 'Cengage' },

  // Magnetism, Nanotechnology, Textiles (Pages 22–23)
  { accNo: 'T50764', accDate: '25/11/2025', title: 'Particulate and granular magnetism', author: 'Oxford University Press Team', publisher: 'Oxford University Press' },
  { accNo: 'T50765', accDate: '25/11/2025', title: 'Nanomagnetism an interdisciplinary approach', author: 'CRC Authors', publisher: 'CRC Press' },
  { accNo: 'T50766', accDate: '25/11/2025', title: 'Energy autonomous micro and nano systems', author: 'Wiley Authors', publisher: 'Wiley' },
  { accNo: 'T50767', accDate: '25/11/2025', title: 'Nano Lithography', author: 'Wiley Authors', publisher: 'Wiley' },
  { accNo: 'T50768', accDate: '25/11/2025', title: 'Nanomaterials handbook 2nd ed', author: 'Gogotsi', publisher: 'CRC Press' },
  { accNo: 'T50769', accDate: '25/11/2025', title: 'Stimuli responsive hydrogels for ophthalmic drug delivery', author: 'Woodhead Authors', publisher: 'Woodhead Publishing' },
  { accNo: 'T50770', accDate: '25/11/2025', title: 'Metal nanoparticles synthesis and applications in pharmaceutical sciences', author: 'Wiley Authors', publisher: 'Wiley' },
  { accNo: 'T50941', accDate: '06/02/2026', title: 'Handbook of technical textile', author: 'Richard', publisher: 'Elsevier' },
  { accNo: 'T50942', accDate: '06/02/2026', title: 'Handbook of technical textile', author: 'Richard', publisher: 'Elsevier' },
  { accNo: 'T50944', accDate: '06/02/2026', title: 'Conventional textiles and textile crafts of India', author: 'Das', publisher: 'CRC Press' },
  { accNo: 'T50943', accDate: '06/02/2026', title: 'Conventional textiles and textile crafts of India', author: 'Das', publisher: 'CRC Press' },
  { accNo: 'T50945', accDate: '06/02/2026', title: 'Testing of textile and fibrous materials', author: 'Das', publisher: 'CRC Press' },
  { accNo: 'T50948', accDate: '06/02/2026', title: 'Wool fiber reinforced polymer composites', author: 'Thomas', publisher: 'Elsevier' },
  { accNo: 'T50949', accDate: '06/02/2026', title: 'Wool fiber reinforced polymer composites', author: 'Thomas', publisher: 'Elsevier' },
  { accNo: 'T50947', accDate: '06/02/2026', title: 'Textile circulation fibre to finished garment', author: 'Chattopadhyay', publisher: 'Woodhead Publishing' },
  { accNo: 'T50946', accDate: '06/02/2026', title: 'Textile circulation fibre to finished garment', author: 'Chattopadhyay', publisher: 'Woodhead Publishing' },
  { accNo: 'T50950', accDate: '06/02/2026', title: 'Artificial intelligence fundamentals and applications', author: 'CRC Authors', publisher: 'CRC Press' },
  { accNo: 'T50951', accDate: '06/02/2026', title: 'Artificial intelligence technologies applications and challenges', author: 'Sharr Lavanya', publisher: 'CRC Press' },

  // ==========================================
  // F.Y. 2024 to 2025 (Pages 1–23)
  // ==========================================
  { accNo: 'T50444', accDate: '19/01/2025', title: 'Introduction to Quantum Computing', author: 'LaPierre Ray', publisher: 'Springer' },
  { accNo: 'T50445', accDate: '19/01/2025', title: 'Deep generative modeling', author: 'Tomczak Jakub M.', publisher: 'Springer' },
  { accNo: 'T50446', accDate: '19/01/2025', title: 'Explainable AI with Python', author: 'Giangagna Leonida', publisher: 'Springer' },
  { accNo: 'T50447', accDate: '19/01/2025', title: 'Kernel methods for machine learning with Math and R : 100 exercises for building Logic', author: 'Suzuki Joe', publisher: 'Springer' },
  { accNo: 'T50448', accDate: '19/01/2025', title: 'Discrete mathematics with coding', author: 'Junghenn Hugo D.', publisher: 'CRC Press' },
  { accNo: 'T50449', accDate: '19/01/2025', title: 'Computer vision : statistical models for Marrs paradigm', author: 'Zhu Song-Chun', publisher: 'CRC Press' },
  { accNo: 'T50450', accDate: '19/01/2025', title: 'Deep learning architectures : a mathematical approach', author: 'Calin Ovidiu', publisher: 'Springer' },
  { accNo: 'T50451', accDate: '19/01/2025', title: 'Dive into deep learning', author: 'Zhang Aston', publisher: 'Cambridge University Press' },
  { accNo: 'T50438', accDate: '20/01/2025', title: 'Practical statistics for data scientists : 50 + essential concepts using R and Python', author: 'Bruce Peter', publisher: 'Shroff Publishers' },
  { accNo: 'T50439', accDate: '20/01/2025', title: 'Machine learning for computer and cyber security : principles, algorithms and practices', author: 'Gupta Brij B.', publisher: 'CRC Press' },
  { accNo: 'T50440', accDate: '20/01/2025', title: 'Mathematics for machine learning', author: 'Deisenroth Marc Peter', publisher: 'Cambridge University Press' },
  { accNo: 'T50441', accDate: '20/01/2025', title: 'Performance analysis of parallel applications for HPC', author: 'Zhai Jidong', publisher: 'Springer' },
  { accNo: 'T50442', accDate: '20/01/2025', title: 'Advancing into analytics : from Excel to Python and R', author: 'Mount George', publisher: 'Shroff Publishers' },
  { accNo: 'T50443', accDate: '20/01/2025', title: 'Network security through data analysis : from data to action', author: 'Collins Michael', publisher: 'Shroff Publishers' },
  { accNo: 'T50452', accDate: '20/01/2025', title: 'An introduction to number theory with cryptography', author: 'Kraft James', publisher: 'CRC Press' },
  { accNo: 'T50453', accDate: '20/01/2025', title: 'Deep reinforcement learning', author: 'Plaat Aske', publisher: 'Springer' },
  { accNo: 'T50454', accDate: '20/01/2025', title: 'Linear algebra for data science, machine learning and signal processing', author: 'Fessler Jeffrey A.', publisher: 'Cambridge University Press' },
  { accNo: 'T50455', accDate: '20/01/2025', title: 'Verifiable autonomous systems : using rational agents to provide assurance about decisions made by machines', author: 'Dennis Louise A.', publisher: 'Cambridge University Press' },
  { accNo: 'T50456', accDate: '20/01/2025', title: 'Natural language processing : a machine learning perspective', author: 'Zhang Yue', publisher: 'Cambridge University Press' },
  { accNo: 'T50457', accDate: '20/01/2025', title: 'Topics in algorithmic graph theory', author: 'Beineke Lowell W.', publisher: 'Cambridge University Press' },
  { accNo: 'T50482', accDate: '12/01/2025', title: 'Introduction to machine learning', author: 'Alpaydin Ethem', publisher: 'The MIT Press' },
  { accNo: 'T50468', accDate: '12/01/2025', title: 'Clinical methods in pain medicine', author: 'Das Gautam', publisher: 'CBS Publishers' },
  { accNo: 'T50469', accDate: '12/01/2025', title: 'Formation control of multiple autonomous vehicle systems', author: 'Liu Hugh H. T.', publisher: 'John Wiley' },
  { accNo: 'T50470', accDate: '12/01/2025', title: 'Random Signal processing', author: 'Apte Shaila Dinkar', publisher: 'CRC Press' },
  { accNo: 'T50471', accDate: '12/01/2025', title: 'Introduction to deep learning for healthcare', author: 'Xiao Cao', publisher: 'Springer' },
  { accNo: 'T50472', accDate: '12/01/2025', title: 'Data science and predictive analytics', author: 'Dinov Ivo D.', publisher: 'Springer' },
  { accNo: 'T50473', accDate: '12/01/2025', title: 'Introduction to digital signal processing using MATLAB with application to digital communications', author: 'Thyagarajan K. S.', publisher: 'Springer' },
  { accNo: 'T50474', accDate: '12/01/2025', title: 'Applied mathematics for the analysis of biomedical data', author: 'Costa Peter J.', publisher: 'John Wiley' },
  { accNo: 'T50475', accDate: '12/01/2025', title: 'Modeling and modern control of wind power', author: 'Wu Qiuwei', publisher: 'John Wiley' },
  { accNo: 'T50476', accDate: '12/01/2025', title: 'Model predictive control of microgrids', author: 'Bordons Carlos', publisher: 'Springer' },
  { accNo: 'T50477', accDate: '12/01/2025', title: 'Signal analysis of hindustani classical music', author: 'Datta Asoke Kumar', publisher: 'Springer' },
  { accNo: 'T50478', accDate: '12/01/2025', title: 'Robotics vision and control : fundamental algorithms in python', author: 'Corke Peter', publisher: 'Springer' },
  { accNo: 'T50479', accDate: '12/01/2025', title: 'Modeling and analysis with induction generators', author: 'Simoes M. Godoy', publisher: 'CRC Press' },
  { accNo: 'T50480', accDate: '12/01/2025', title: 'Handbook of functional MRI data analysis', author: 'Poldrack Russell A.', publisher: 'Cambridge University Press' },
  { accNo: 'T50481', accDate: '12/01/2025', title: 'Dive into deep learning', author: 'Zhang Aston', publisher: 'Cambridge University Press' },
  { accNo: 'T50467', accDate: '13/01/2025', title: 'Introduction to machine learning', author: 'Alpaydin Ethem', publisher: 'The MIT Press' },
  { accNo: 'T50483', accDate: '13/01/2025', title: 'Communication systems', author: 'Sharma S', publisher: 'Kataria' },
  { accNo: 'T50484', accDate: '13/01/2025', title: 'Communication systems', author: 'Sharma S', publisher: 'Kataria' },
  { accNo: 'T50486', accDate: '13/01/2025', title: 'Mathematical Physics', author: 'Das H. K.', publisher: 'S. Chand & Co' },
  { accNo: 'T50489', accDate: '13/01/2025', title: 'Mathematical Physics', author: 'Das H. K.', publisher: 'S. Chand & Co' },
  { accNo: 'T50488', accDate: '13/01/2025', title: 'Mathematical Physics', author: 'Das H. K.', publisher: 'S. Chand & Co' },
  { accNo: 'T50487', accDate: '13/01/2025', title: 'Mathematical Physics', author: 'Das H. K.', publisher: 'S. Chand & Co' },
  { accNo: 'T50485', accDate: '13/01/2025', title: 'Mathematical Physics', author: 'Das H. K.', publisher: 'S. Chand & Co' },
  { accNo: 'T50490', accDate: '13/01/2025', title: 'Machine learning', author: 'Dutt S.', publisher: 'Pearson' },
  { accNo: 'T50492', accDate: '13/01/2025', title: 'Machine learning', author: 'Dutt S.', publisher: 'Pearson' },
  { accNo: 'T50491', accDate: '13/01/2025', title: 'Machine learning', author: 'Dutt S.', publisher: 'Pearson' },
  { accNo: 'T50493', accDate: '13/01/2025', title: 'GATE 2025 : Electrical Engineering', author: 'Singh B.', publisher: 'Made Easy Publications' },
  { accNo: 'T50494', accDate: '13/01/2025', title: 'Engineering electromagnetic', author: 'Hayt William H.', publisher: 'McGraw Hill' },
  { accNo: 'T50495', accDate: '13/01/2025', title: 'Engineering electromagnetic', author: 'Hayt William H.', publisher: 'McGraw Hill' },
  { accNo: 'T50496', accDate: '13/01/2025', title: 'Engineering electromagnetic', author: 'Hayt William H.', publisher: 'McGraw Hill' },
  { accNo: 'T50497', accDate: '13/01/2025', title: 'Engineering electromagnetic', author: 'Hayt William H.', publisher: 'McGraw Hill' },
  { accNo: 'T50498', accDate: '13/01/2025', title: 'Engineering electromagnetic', author: 'Hayt William H.', publisher: 'McGraw Hill' },
  { accNo: 'T50503', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50502', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50501', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50505', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50504', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50500', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50499', accDate: '13/01/2025', title: 'Process control : principles and applications', author: 'Bhanot S.', publisher: 'Oxford University Press' },
  { accNo: 'T50506', accDate: '13/01/2025', title: 'Power electronics', author: 'Bimbhra P. S.', publisher: 'Khanna' },
  { accNo: 'T50507', accDate: '13/01/2025', title: 'Power electronics', author: 'Bimbhra P. S.', publisher: 'Khanna' },
  { accNo: 'T50508', accDate: '13/01/2025', title: 'Electrical machines : fundamentals of electromechanical energy conversion', author: 'Gieras J. F.', publisher: 'CRC Press' },
  { accNo: 'T50509', accDate: '13/01/2025', title: 'Fundamentals of electric machines', author: 'Sadiku M. N. O.', publisher: 'CRC Press' },
  { accNo: 'T50510', accDate: '13/01/2025', title: 'Python for scientific computing and artificial intelligence', author: 'Lynch S.', publisher: 'CRC Press' },
  { accNo: 'T50511', accDate: '13/01/2025', title: 'Swarm intelligence', author: 'Emary E.', publisher: 'CRC Press' },
  { accNo: 'T50512', accDate: '13/01/2025', title: 'Electric and hybrid vehicles', author: 'Husain I.', publisher: 'CRC Press' },
  { accNo: 'T50513', accDate: '13/01/2025', title: 'Power electronics : advanced conversion technologies', author: 'Luo F. L.', publisher: 'CRC Press' },
  { accNo: 'T50514', accDate: '13/01/2025', title: 'Instrumentation engineering : previous solved papers Gate 2025', author: 'Singh B.', publisher: 'Made Easy Publications' },
  { accNo: 'T50462', accDate: '13/01/2025', title: 'Mathematics for machine learning', author: 'Deisenroth Marc Peter', publisher: 'Cambridge University Press' },
  { accNo: 'T50463', accDate: '13/01/2025', title: 'Learning deep learning', author: 'Ekman Magnus', publisher: 'Pearson' },
  { accNo: 'T50464', accDate: '13/01/2025', title: 'Learning deep learning', author: 'Ekman Magnus', publisher: 'Pearson' },
  { accNo: 'T50465', accDate: '13/01/2025', title: 'Digital signal processing for medical imaging using MATLAB', author: 'Gopi E. S.', publisher: 'Springer' },
  { accNo: 'T50466', accDate: '13/01/2025', title: 'Fuzzy system identification and adaptive control', author: 'Gangtao Ruiyon Qi', publisher: 'Springer' },

  // Mechanics, Optics, Materials
  { accNo: 'T50427', accDate: '05/02/2025', title: 'Wavelet transforms : kith and kin', author: 'Shah Firdous A.', publisher: 'CRC Press' },
  { accNo: 'T50428', accDate: '05/02/2025', title: 'Graphene for flexible lighting and displays', author: 'Lee Tae-Woo', publisher: 'Elsevier' },
  { accNo: 'T50429', accDate: '05/02/2025', title: 'Laser printing of functional materials : 3D microfabrication, electronics and biomedicine', author: 'Pique Alberto', publisher: 'Wiley' },
  { accNo: 'T50430', accDate: '05/02/2025', title: 'Greens function integral equation methods in nano-optics', author: 'Sondergaard Thomas M.', publisher: 'CRC Press' },
  { accNo: 'T50431', accDate: '05/02/2025', title: 'Understanding surface and thin film science', author: 'Christensen Thomas M.', publisher: 'CRC Press' },
  { accNo: 'T50432', accDate: '05/02/2025', title: 'Fundamentals of optical waves and lasers', author: 'Yoshida Sanichiro', publisher: 'Springer' },
  { accNo: 'T50433', accDate: '05/02/2025', title: 'Introduction to laser science and engineering', author: 'Taylor Travis S.', publisher: 'CRC Press' },
  { accNo: 'T50434', accDate: '05/02/2025', title: 'Nanophotonics and machine learning : concepts, fundamentals and applications', author: 'Yao Kan', publisher: 'Springer' },
  { accNo: 'T50435', accDate: '05/02/2025', title: 'Semiconductor laser photonics', author: 'Nisoli Mauro', publisher: 'Cambridge University Press' },
  { accNo: 'T50436', accDate: '05/02/2025', title: '3D printing of optical components', author: 'Heinrich Andreas', publisher: 'Springer' },
  { accNo: 'T50414', accDate: '06/02/2025', title: 'Advances in speckle metrology and related techniques', author: 'Kaufmann Guillermo H.', publisher: 'Wiley' },
  { accNo: 'T50415', accDate: '06/02/2025', title: 'Introduction to modern digital holography with MATLAB', author: 'Poon Ting-Chung', publisher: 'Cambridge University Press' },
  { accNo: 'T50416', accDate: '06/02/2025', title: 'Concise optics : concepts, examples and problems', author: 'Haija Ajawad I.', publisher: 'CRC Press' },
  { accNo: 'T50417', accDate: '06/02/2025', title: 'Nonlinear effects in optical fibers', author: 'Ferreira Mario F. S.', publisher: 'Wiley' },
  { accNo: 'T50418', accDate: '06/02/2025', title: 'Ultra-realistic imaging : advanced techniques in analogue and digital colour holography', author: 'Bjelkhagen Hans', publisher: 'CRC Press' },
  { accNo: 'T50419', accDate: '09/02/2025', title: 'Modern atomic and nuclear physics', author: 'Gupta A. B.', publisher: 'Books & Allied' },
  { accNo: 'T50420', accDate: '09/02/2025', title: 'Modern optics', author: 'Gupta A. B.', publisher: 'Books & Allied' },
  { accNo: 'T50421', accDate: '09/02/2025', title: 'Fundamentals of mathematical physics', author: 'Gupta A. B.', publisher: 'Books & Allied' },
  { accNo: 'T50422', accDate: '09/02/2025', title: 'Nanostructured and subwavelength waveguides : fundamentals and applications', author: 'Skorobogatiy Maksim', publisher: 'Wiley' },
  { accNo: 'T50423', accDate: '09/02/2025', title: 'Digital circuits and design', author: 'Salivahanan S.', publisher: 'Oxford University Press' },
  { accNo: 'T50424', accDate: '09/02/2025', title: 'Introduction to solid state physics', author: 'Kittel Charles', publisher: 'Wiley India' },
  { accNo: 'T50425', accDate: '09/02/2025', title: 'Nanomaterials : theory problems and solutions', author: 'Nandi Upendranath', publisher: 'Techno World' },
  { accNo: 'T50426', accDate: '09/02/2025', title: 'Statistical mechanics : theory problems and solutions', author: 'Nandi Upendranath', publisher: 'Techno World' },

  // Shroff Books, O'Reilly reprints (Pages 9–10)
  { accNo: 'T50683', accDate: '28/01/2025', title: 'Fundamentals of deep learning : designing next generation machine intelligence algorithms', author: 'Buduma Nithin', publisher: 'Shroff Publishers' },
  { accNo: 'T50684', accDate: '28/01/2025', title: 'Hands-on machine learning with Scikit-Learn, Keras and TensorFlow', author: 'Geron Aurelien', publisher: 'Shroff Publishers' },
  { accNo: 'T50685', accDate: '28/01/2025', title: 'Data structures and algorithms using Python and C++', author: 'Reed David M.', publisher: 'Shroff Publishers' },
  { accNo: 'T50686', accDate: '28/01/2025', title: 'Modern programming languages : a practical introduction', author: 'Webber Adam Brooks', publisher: 'Shroff Publishers' },
  { accNo: 'T50687', accDate: '28/01/2025', title: 'A common-sense guide to data structures and algorithms in Python : level up your core', author: 'Wengrow Jay', publisher: 'Shroff Publishers' },
  { accNo: 'T50688', accDate: '28/01/2025', title: 'Make : basic Arduino project : 26 experiments with microcontrollers and electronics', author: 'Wilcher Don', publisher: 'Shroff Publishers' },
  { accNo: 'T50689', accDate: '28/01/2025', title: 'Getting started with the internet of things', author: 'Pfister Cuno', publisher: 'Shroff Publishers' },
  { accNo: 'T50691', accDate: '28/01/2025', title: 'The DevOps handbook : how to create world-class agility, reliability and security in technology organizations', author: 'Kim Gene', publisher: 'Shroff Publishers' },
  { accNo: 'T50690', accDate: '28/01/2025', title: 'The DevOps handbook : how to create world-class agility, reliability and security in technology organizations', author: 'Kim Gene', publisher: 'Shroff Publishers' },
  { accNo: 'T50692', accDate: '28/01/2025', title: 'Agile application security : enabling security in a continuous delivery pipeline', author: 'Bell Laura', publisher: 'Shroff Publishers' },
  { accNo: 'T50693', accDate: '28/01/2025', title: 'Essential math for data science : take control of your data with fundamental linear algebra, probability and statistics', author: 'Nield Thomas', publisher: 'Shroff Publishers' },
  { accNo: 'T50694', accDate: '28/01/2025', title: 'Practical machine learning for computer vision : end to end machine learning for images', author: 'Lakshmanan Valliappa', publisher: 'Shroff Publishers' },
  { accNo: 'T50674', accDate: '14/01/2025', title: 'Modern programming languages', author: 'Adam Brooks Webber', publisher: 'Shroff Publishers' },
  { accNo: 'T50675', accDate: '14/01/2025', title: 'Programming Language Implementation', author: 'Hamel Lutz', publisher: 'Shroff Publishers' },
  { accNo: 'T50676', accDate: '14/01/2025', title: 'Problem solving with algorithms and data structures using Python', author: 'Miller Bradley N.', publisher: 'Shroff Publishers' },
  { accNo: 'T50677', accDate: '14/01/2025', title: 'Techniques for designing and analyzing algorithms', author: 'Stinson Douglas R.', publisher: 'CRC Press' },
  { accNo: 'T50678', accDate: '14/01/2025', title: 'Parameterized Algorithms', author: 'Cygan Marek', publisher: 'Springer' },
  { accNo: 'T50679', accDate: '14/01/2025', title: 'Cryptography', author: 'Rubinstein-Salzedo Simon', publisher: 'Springer' },

  // Narosa & Academic Texts (Pages 12–15)
  { accNo: 'T50669', accDate: '15/01/2025', title: 'The elements of statistical learning : data mining, inference and prediction', author: 'Hastie Trevor', publisher: 'Springer' },
  { accNo: 'T50670', accDate: '15/01/2025', title: 'Neural networks and statistical learning', author: 'Du Ke-Lin', publisher: 'Springer' },
  { accNo: 'T50671', accDate: '15/01/2025', title: 'Algebraic combinatorics : walks, trees, tableaux and more', author: 'Stanley Richard P.', publisher: 'Springer' },
  { accNo: 'T50672', accDate: '15/01/2025', title: 'Discrete mathematics and functional programming', author: 'VanDrunen Thomas', publisher: 'Shroff Publishers' },
  { accNo: 'T50673', accDate: '15/01/2025', title: 'Data structures and algorithms using Python and C++', author: 'Reed David M.', publisher: 'Shroff Publishers' },
  { accNo: 'T50698', accDate: '15/01/2025', title: 'Data structures and algorithms with Python', author: 'Lee Kent D.', publisher: 'Springer' },
  { accNo: 'T50699', accDate: '15/01/2025', title: 'Fundamentals of quantum computing : theory and practice', author: 'Kasirajan Venkateswaran', publisher: 'Springer' },
  { accNo: 'T50700', accDate: '15/01/2025', title: 'Elements of data science, machine learning and artificial intelligence using R', author: 'Emmert-Strelb Frank', publisher: 'Springer' },
  { accNo: 'T50701', accDate: '15/01/2025', title: 'Geometry of deep learning', author: 'Ye Jong Chul', publisher: 'Springer' },
  { accNo: 'T50660', accDate: '15/01/2025', title: 'Machine learning for TEXT', author: 'Aggarwal Charu C', publisher: 'Springer' },
  { accNo: 'T50656', accDate: '15/01/2025', title: 'Machine learning for TEXT', author: 'Aggarwal Charu C', publisher: 'Springer' },
  { accNo: 'T50658', accDate: '15/01/2025', title: 'Machine learning for TEXT', author: 'Aggarwal Charu C', publisher: 'Springer' },
  { accNo: 'T50657', accDate: '15/01/2025', title: 'Machine learning for TEXT', author: 'Aggarwal Charu C', publisher: 'Springer' },
  { accNo: 'T50659', accDate: '15/01/2025', title: 'Machine learning for TEXT', author: 'Aggarwal Charu C', publisher: 'Springer' },
  { accNo: 'T50661', accDate: '15/01/2025', title: 'Natural language processing', author: 'Lee Raymond S. T.', publisher: 'Springer' },
  { accNo: 'T50662', accDate: '15/01/2025', title: 'Natural language processing', author: 'Lee Raymond S. T.', publisher: 'Springer' },
  { accNo: 'T50665', accDate: '15/01/2025', title: 'Deep reinforcement learning', author: 'Plaat Aske', publisher: 'Springer' },
  { accNo: 'T50663', accDate: '15/01/2025', title: 'Deep reinforcement learning', author: 'Plaat Aske', publisher: 'Springer' },
  { accNo: 'T50664', accDate: '15/01/2025', title: 'Deep reinforcement learning', author: 'Plaat Aske', publisher: 'Springer' },
  { accNo: 'T50629', accDate: '15/01/2025', title: 'An integrated approach to software engineering', author: 'Jalote Pankaj', publisher: 'Narosa' },
  { accNo: 'T50630', accDate: '15/01/2025', title: 'An integrated approach to software engineering', author: 'Jalote Pankaj', publisher: 'Narosa' },
  { accNo: 'T50631', accDate: '15/01/2025', title: 'Computer based optimization techniques', author: 'Agarwal Subham', publisher: 'Narosa' },
  { accNo: 'T50632', accDate: '15/01/2025', title: 'Data mining methods', author: 'Chattamvelli Rajan', publisher: 'Narosa' },
  { accNo: 'T50634', accDate: '15/01/2025', title: 'Data mining methods', author: 'Chattamvelli Rajan', publisher: 'Narosa' },
  { accNo: 'T50633', accDate: '15/01/2025', title: 'Data mining methods', author: 'Chattamvelli Rajan', publisher: 'Narosa' },
  { accNo: 'T50635', accDate: '15/01/2025', title: 'Graph theory', author: 'Chatterjee Dipak', publisher: 'Narosa' },
  { accNo: 'T50636', accDate: '15/01/2025', title: 'Graph theory', author: 'Harary F.', publisher: 'Narosa' },
  { accNo: 'T50639', accDate: '15/01/2025', title: 'Modern approaches of data mining', author: 'Panda M.', publisher: 'Narosa' },
  { accNo: 'T50638', accDate: '15/01/2025', title: 'Modern approaches of data mining', author: 'Panda M.', publisher: 'Narosa' },
  { accNo: 'T50637', accDate: '15/01/2025', title: 'Modern approaches of data mining', author: 'Panda M.', publisher: 'Narosa' },
  { accNo: 'T50640', accDate: '15/01/2025', title: 'Multi-layer channel routing', author: 'Pal R. K.', publisher: 'Narosa' },
  { accNo: 'T50641', accDate: '15/01/2025', title: 'Multi-layer channel routing', author: 'Pal R. K.', publisher: 'Narosa' },
  { accNo: 'T50642', accDate: '15/01/2025', title: 'Optimization theory and practice', author: 'Joshi M. C.', publisher: 'Narosa' },
  { accNo: 'T50643', accDate: '15/01/2025', title: 'Software engineering : a practitioners approach', author: 'Khan R. A.', publisher: 'Narosa' },
  { accNo: 'T50644', accDate: '15/01/2025', title: 'Software quality assurance', author: 'Godbole N. S.', publisher: 'Narosa' },
  { accNo: 'T50645', accDate: '15/01/2025', title: 'VLSI design', author: 'Basu D. K.', publisher: 'Narosa' },
  { accNo: 'T50655', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50648', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50647', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50652', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50646', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50651', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50650', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50649', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50653', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },
  { accNo: 'T50654', accDate: '15/01/2025', title: 'Discrete mathematical structures', author: 'Das M. K.', publisher: 'Narosa' },

  // Mechanics, Thermal, Textbooks (Pages 22–23)
  { accNo: 'T50613', accDate: '19/12/2024', title: 'A textbook of refrigeration and air conditioning', author: 'Khurmi R. S.', publisher: 'S. Chand & Co' },
  { accNo: 'T50612', accDate: '19/12/2024', title: 'A textbook of refrigeration and air conditioning', author: 'Khurmi R. S.', publisher: 'S. Chand & Co' },
  { accNo: 'T50614', accDate: '19/12/2024', title: 'Steam tables with mollier diagram in S.I. units', author: 'Khurmi R. S.', publisher: 'S. Chand & Co' },
  { accNo: 'T50615', accDate: '19/12/2024', title: 'Steam tables with mollier diagram in S.I. units', author: 'Khurmi R. S.', publisher: 'S. Chand & Co' },
  { accNo: 'T50617', accDate: '19/12/2024', title: 'Applied mechanics and strength of materials', author: 'Khurmi R. S.', publisher: 'S. Chand & Co' },
  { accNo: 'T50616', accDate: '19/12/2024', title: 'Applied mechanics and strength of materials', author: 'Khurmi R. S.', publisher: 'S. Chand & Co' },
  { accNo: 'T50618', accDate: '19/12/2024', title: 'A textbook of fluid mechanics and hydraulic mechanics', author: 'Bansal R. K.', publisher: 'Laxmi Publications' },
  { accNo: 'T50619', accDate: '19/12/2024', title: 'A textbook of fluid mechanics and hydraulic mechanics', author: 'Bansal R. K.', publisher: 'Laxmi Publications' },
];

if (process.argv[1]?.includes('run_import')) {
  importEntries(cuRecords);
}
